
name: 'airflow_dbt_template'
version: '0.1.0'
require-dbt-version: '>=1.0.0'

profile: 'airflow_dbt_template'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_dbt_template:
    example:
      +enabled: false
    bronze:
      +tags: bronze
    silver:
      +tags: silver
