version: 2.1

jobs:
  lint-build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r python_scripts/requirements.txt
            pip install -r tests/test-requirements.txt
      - run:
          name: Run linting with Ruff
          command: |
            . venv/bin/activate
            ruff check .
      - run:
          name: Run project structure tests
          command: |
            . venv/bin/activate
            pytest tests/test_project_structure.py -v
      - run:
          name: Run DAG import tests
          command: |
            . venv/bin/activate
            pytest --cov=dags tests/ -v

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "EC2_PUBLIC_KEY"
      - run:
          name: Sync code to EC2
          command: |
            rsync -avz --delete \
              --exclude='.git/*' \
              ./ ${EC2_USER}@${EC2_PUBLIC_IP}:/opt/airflow-dbt-template/
      - run:
          name: Restart Airflow services
          command: |
            ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_PUBLIC_IP} \<< 'EOF'
              sudo docker compose down
              sudo docker compose up -d
            EOF

workflows:
  version: 2
  ci-deploy:
    jobs:
      - lint-build-and-test
      - deploy:
          requires:
            - lint-build-and-test
          filters:
            branches:
              only: main
